error_page 403 /error.html?code=403;
error_page 404 /error.html?code=404;
error_page 500 502 503 504 /error.html?code=500;

location = /.env {
  deny all;
}

location ~ ^/\.env(?:\..*)?$ {
  deny all;
}

location ~ ^/(?:custom|functions|autoload)\.php$ {
  deny all;
}

location ~ ^/(?:config|src|logs)/ {
  deny all;
}

location / {
  try_files $uri $uri/ /index.php?$query_string;
}
